# NumPy 

A NumPy array is an alternative to regular Python lists.

Lists are great, but you can't perform many operations over them. 

In [1]:
x = [2, 3, 10]
d = [10, 10, 10]

2 * x

[2, 3, 10, 2, 3, 10]

In [2]:
x/d

TypeError: unsupported operand type(s) for /: 'list' and 'list'

## Importing NumPy

To fix this, we're going to use the code you see below. First we need to import numpy, so it is available in our environment. 

We haven't imported many libraries. Somewhat (well really) unofficially, a library is a collection of other code that works together to help you solve a problem. NumPy is a library, but you will often hear people (me too) call it a package. Packages have a different specific definition. At this point in your Python journey... I don't think you should worry to much about the differences between the two!

In [3]:
import numpy as np

Now we can convert the lists we have, to a numpy array

In [4]:
x = [2, 3, 10]
d = [2, 10, 100000]

np_x = np.array(x)
np_x

array([ 2,  3, 10])

In [5]:
np_d = np.array(d)
np_d

array([     2,     10, 100000])

Now we can do element wise operations. In the below operation, 2 is broadcast to the elements of the numpy array. Each value in the numpy array is multiplied by the same value. 

In [6]:
2 * np_x

array([ 4,  6, 20])

In [7]:
np_x/np_d

array([1.e+00, 3.e-01, 1.e-04])

But if you create an array with a different number of elements (it has a different shape, you run into an error)

In [8]:
y = [2,3]
np_y = np.array(y)
np_y * np_x

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

## NumPy 2D

Lets create a slightly more complex array. 


In [9]:
# using variable inputs
a = [6.1, 5.8, 5.97, 5.43, 7.34, 8.67, 6.55, 3.66, 2.31, 6.84]
b = [2.5, 3.19, 2.26, 3.17, 8.17, 2.76, 5.22, 9.82, 3.95, 8.38]

np_a = np.array(a)
np_b = np.array(b)


In [10]:
Numpy2d = np.array([a,b])
print(Numpy2d.shape)
print(Numpy2d)             

(2, 10)
[[6.1  5.8  5.97 5.43 7.34 8.67 6.55 3.66 2.31 6.84]
 [2.5  3.19 2.26 3.17 8.17 2.76 5.22 9.82 3.95 8.38]]


In [11]:
#side note... '.shape' returns the shape of the array as a tuple
Numpy2d.shape

(2, 10)

In [12]:
Transposed_array = np.array([a,b]).T
print(Transposed_array.shape)
Transposed_array

(10, 2)


array([[6.1 , 2.5 ],
       [5.8 , 3.19],
       [5.97, 2.26],
       [5.43, 3.17],
       [7.34, 8.17],
       [8.67, 2.76],
       [6.55, 5.22],
       [3.66, 9.82],
       [2.31, 3.95],
       [6.84, 8.38]])

## Selecting from arrays

In [13]:
# using variable inputs
a = [6.1, 5.8, 5.97, 5.43, 7.34, 8.67, 6.55, 3.66, 2.31, 6.84]
b = [2.5, 3.19, 2.26, 3.17, 8.17, 2.76, 5.22, 9.82, 3.95, 8.38]

matrixEx = np.array([a,b])
print(matrixEx.shape)


(2, 10)


If you use np.matrix, you will get a 2d array. If you use np.array with two lists, you will also get a 2d array. 

In [14]:
matrixEx = np.matrix([a,b])
print(matrixEx.shape)

(2, 10)


In [15]:
print(matrixEx) 

[[6.1  5.8  5.97 5.43 7.34 8.67 6.55 3.66 2.31 6.84]
 [2.5  3.19 2.26 3.17 8.17 2.76 5.22 9.82 3.95 8.38]]


Now that we have this array, what can subset and select from it (just like a list). 

An array can have a large number of dimensions. When it has two dimensions (a "2d" array) like this one, you can think of the first position as the ROW, and the second position is the COLUMN. But if you add more dimensions, this thinking doesn't really work! All you really need to get a handle on is the position within an array (1, 2 etc). 


In [16]:
matrixEx[0,1]

5.8

In [17]:
matrixEx[1,0]

2.5

In [18]:
# Bigger matrix example
np.random.seed(1955)
x = np.random.randn(3, 3, 3, 3)
print(x.shape)
x

(3, 3, 3, 3)


array([[[[-0.3077721 ,  0.60127275,  0.37351551],
         [-1.66625832, -0.67932425,  0.16827459],
         [ 0.5285291 ,  1.98193067,  0.50847906]],

        [[-0.97761802,  0.16285869, -0.22122161],
         [-0.72708872,  1.1979344 ,  0.57646273],
         [ 0.44571315, -1.10823726, -1.07857182]],

        [[ 0.54880424,  0.70573608,  0.5987767 ],
         [-0.75783048,  1.45763527,  0.14773223],
         [ 0.16026624, -0.80708282,  0.64622708]]],


       [[[-1.77862159, -0.42635618,  1.68164745],
         [ 0.12505723,  0.47472168,  0.72371026],
         [ 0.8783094 , -1.36746711, -0.15616154]],

        [[-0.35064363,  0.50239732,  0.12665901],
         [ 0.7235746 , -0.23263002,  0.11652987],
         [ 0.00827123, -0.74261187,  0.09650545]],

        [[ 1.14529644, -1.4825064 , -0.10443137],
         [ 1.12201509, -0.47028513, -0.57333802],
         [ 0.8217387 ,  1.40802217, -0.39207849]]],


       [[[ 0.53804766, -0.17409249, -0.47726962],
         [-1.63922969, -2.36091367

In [19]:
x[0]

array([[[-0.3077721 ,  0.60127275,  0.37351551],
        [-1.66625832, -0.67932425,  0.16827459],
        [ 0.5285291 ,  1.98193067,  0.50847906]],

       [[-0.97761802,  0.16285869, -0.22122161],
        [-0.72708872,  1.1979344 ,  0.57646273],
        [ 0.44571315, -1.10823726, -1.07857182]],

       [[ 0.54880424,  0.70573608,  0.5987767 ],
        [-0.75783048,  1.45763527,  0.14773223],
        [ 0.16026624, -0.80708282,  0.64622708]]])

In [20]:
x[0, 0]

array([[-0.3077721 ,  0.60127275,  0.37351551],
       [-1.66625832, -0.67932425,  0.16827459],
       [ 0.5285291 ,  1.98193067,  0.50847906]])

In [21]:
x[0, 0, 0]

array([-0.3077721 ,  0.60127275,  0.37351551])

In [22]:
x[0, 0, 0, 0]

-0.307772100470304

## Statistics

NumPy arrays allow us to perform some basic statistical queries on the data as well. This is a really good way to "get to know" your data.  

In [23]:
a = [6.1, 5.8, 5.97, 5.43, 7.34, 8.67, 6.55, 3.66, 2.31, 6.84]
b = [2.5, 3.19, 2.26, 3.17, 8.17, 2.76, 5.22, 9.82, 3.95, 8.38]

my_data = np.array([a,b])
print(my_data.shape)

(2, 10)


We can get the mean for all the values...

In [24]:
np.mean(my_data)

5.4045

...or just the first row...

In [25]:
np.mean(my_data[0,:])

5.867

...or just the last row... (etc etc)

In [26]:
np.mean(my_data[1,:])

4.942

These functions are useful, but can breakdown when handling missing data (see text book on "other aggregation functions" for a more thorough review of this idea.). NaN means "Not a number". When you see it in a formula it is probbably there to help complete that operation in the presence of missing values. But try it out!

Function Name |	NaN-safe Version  |	Description
--------------|-------------------|-----
np.sum | np.nansum	| Compute sum of elements
np.prod	|np.nanprod	|Compute product of elements
np.mean	|np.nanmean	|Compute mean of elements
np.std	|np.nanstd	|Compute standard deviation
np.var	|np.nanvar	|Compute variance
np.min	|np.nanmin	|Find minimum value
np.max	|np.nanmax	|Find maximum value
np.argmin	|np.nanargmin	|Find index of minimum value
np.argmax	|np.nanargmax	|Find index of maximum value
np.median	|np.nanmedian	|Compute median of elements
np.percentile	|np.nanpercentile	|Compute rank-based statistics of elements
np.any	|N/A	|Evaluate whether any elements are true
np.all	|N/A	|Evaluate whether all elements are true

The above table is a modified version of the table in the online text book: A Whirlwind Tour of Python by Jake VanderPlas (O’Reilly). Copyright 2016 O’Reilly Media, Inc., 978-1-491-96465-1. Available online at https://jakevdp.github.io/WhirlwindTourOfPython/

## Some limitations

A 2d Numpy array may seem like a great data structure, and it is. Many of the packages used in data analytics and machine learning are built on top of this remarkable set of tools. 

But it has some limitations.

Leading among these, is that Numpy arrays take just one data type.

# Pandas

The 'wine' data in this example comes from: archive.ics.uci.edu. It has been slightly modified to fit into this lesson. Check out some of the other cool machine learning training data sets they have. 

The 'segment' data was created for this example.

## A Quick Introduction

In [27]:
import os
os.getcwd()


'/Users/joeldavis/Library/CloudStorage/OneDrive-UniversityofFlorida/Documents/courses/QMB3302_foundations/QMB3302/notebooks'

In [28]:
import pandas as pd
path= 'mydata.csv'

path = "../data/segments.csv"

seg = pd.read_csv(path)
# to take a peek at the data
# .head() returns the first 5 rows of the dataframe
seg.head(10)

age   Income  Under18AtHome  HomeOwnership  subscribe   Segment
0  45.0  50033.0              4              0          0  Suburban
1  25.0  10835.0              3              0          0     Urban
2  46.0  63281.0              1              0          0  Suburban
3  40.0  46201.0              2              1          0  Suburban
4  41.0  49343.0              1              1          0  Suburban
5  31.0  56718.0              1              0          0  Suburban
6  37.0  70625.0              4              1          1  Suburban
7  38.0  79416.0              2              1          1  Suburban
8  22.0  26357.0              2              0          0     Urban
9  40.0  72770.0              2              0          0  Suburban

What we get above is a table. At it's most basic, this is a rectangular set of data. It has a few properties that I am sure are clear:

* **Rows**: Which represent unique records. 
* **Columns**: Which represent unique characteristics. The columns contain just *one* type of data. 

We can pull out just a column by using it's name, or rows by indexing. Remember to start at 0!

In [29]:
seg["Segment"]

0      Suburban
1         Urban
2      Suburban
3      Suburban
4      Suburban
         ...   
995    Suburban
996       Urban
997     ExUrban
998     ExUrban
999       Urban
Name: Segment, Length: 1000, dtype: object

In [30]:
#includes 0 and 1, but not 2
seg[0:2]

age   Income  Under18AtHome  HomeOwnership  subscribe   Segment
0  45.0  50033.0              4              0          0  Suburban
1  25.0  10835.0              3              0          0     Urban

&nbsp;

&nbsp;

## Importing Data

We have already seen how to import into Pandas. Let's look at some additional nuances. 

### Importing from a csv

This will be the most common way for us to import data (in this class). You are often given a data set as .txt, .csv or .xls file. 

In [31]:
# if the file is in the same directory
import pandas as pd
seg = pd.read_csv("segments.csv")
seg.head()


age   Income  Under18AtHome  HomeOwnership  subscribe   Segment
0  45.0  50033.0              4              0          0  Suburban
1  25.0  10835.0              3              0          0     Urban
2  46.0  63281.0              1              0          0  Suburban
3  40.0  46201.0              2              1          0  Suburban
4  41.0  49343.0              1              1          0  Suburban

A more boilerplate way of doing this is to assign the path and use that. Paths can be relative  to where you are in your folder structure, or absolute. Absolute just means it is the entire path through your computer to that file.  
 

In [32]:
#example of an absolute path
# I can also use more python friendly "/" in the below

import pandas as pd
path = '/Users/joeldavis/Library/CloudStorage/OneDrive-UniversityofFlorida/Documents/courses/QMB3302_foundations/notebooks/data/segments.csv'
seg = pd.read_csv(path)
seg.head()


FileNotFoundError: [Errno 2] No such file or directory: '/Users/joeldavis/Library/CloudStorage/OneDrive-UniversityofFlorida/Documents/courses/QMB3302_foundations/notebooks/data/segments.csv'

In [33]:
# example of a relative path
# for the most part, the rest of this course uses this structure. Where the data is located one file up from my
# current location, and in a file called 'data'
import pandas as pd

path = "../data/segments.csv"
seg = pd.read_csv(path)
seg.head()

age   Income  Under18AtHome  HomeOwnership  subscribe   Segment
0  45.0  50033.0              4              0          0  Suburban
1  25.0  10835.0              3              0          0     Urban
2  46.0  63281.0              1              0          0  Suburban
3  40.0  46201.0              2              1          0  Suburban
4  41.0  49343.0              1              1          0  Suburban

### Importing from Excel

To load an Excel file, just change the "pd.read..." argument. Note that this has the additional parameter "sheet_name", allowing you to extract just one sheet from an excel document. The "header" argument allows you to specify which row to use as a header in your new dataframe. This is helpful when confronted with an Excel document that has been formatted to look pretty, and has multiple spaces before the header row. When faced with this travesty, resist the urge to scold the excel's creator on their mistake.

In [34]:
import pandas as pd

path = "../data/segments.xlsx"
exampleExcel = pd.read_excel(path, sheet_name = 'segments', header = 0)
exampleExcel.head()

please ask Joel if you need more information on this helpful data and structure. You are WELCOME  \
0                                                  1                                                 
1                                 vlookuptoinfinity                                                  
2                                                age                                                 
3                                                 45                                                 
4                                                 25                                                 

  normdbaccu1          calc1     Unnamed: 3 Unnamed: 4  Unnamed: 5  
0           2              3              4          5           6  
1         NaN            NaN            NaN        NaN  and beyond  
2      Income  Under18AtHome  HomeOwnership  subscribe     Segment  
3       50033              4              0          0    Suburban  
4       10835              3              0          0       Urban

In [35]:
import pandas as pd

path = "../data/segments_in_excel.xlsx"
exampleExcel = pd.read_excel(path, sheet_name = 'segments', header = 0)
exampleExcel.head()

1                             2              3  \
0  load data mess  this is an additional header           blue   
1             age                        Income  Under18AtHome   
2              45                         50033              4   
3              25                         10835              3   
4              46                         63281              1   

                           4                  5         6  
0  home owners listed as 0 1  non subscribers 0       NaN  
1              HomeOwnership          subscribe   Segment  
2                          0                  0  Suburban  
3                          0                  0     Urban  
4                          0                  0  Suburban

In [36]:
# Fix that mess!

exampleExcel = pd.read_excel(path, sheet_name = 'segments', header = 2)
exampleExcel.head()

age   Income  Under18AtHome  HomeOwnership  subscribe   Segment
0  45.0  50033.0              4              0          0  Suburban
1  25.0  10835.0              3              0          0     Urban
2  46.0  63281.0              1              0          0  Suburban
3  40.0  46201.0              2              1          0  Suburban
4  41.0  49343.0              1              1          0  Suburban

### Importing from a URL

So this can take us down a rabbit hole. But you will often find data online that you want. You have some options. 

1. Download it, put it in a folder, and then load it up.
2. Use Python to grab it

If the below is too much... don't worry about it. I'll demonstrate how to go get data from somewhere. You can choose whatever method works for you! 

In [37]:
import pandas as pd
import urllib
import os

In [38]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
newpath = os.path.join("../data")
data_path = os.path.join(newpath, "winequality-red.csv")
req = urllib.request.urlretrieve(url, data_path)
web_data = pd.read_csv(data_path, delimiter=';')
web_data.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.36             6.1      0.071   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 17.0                 102.0   0.9978  3.35       0.80   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5  
5      9.4        5  
6      9.4        5  
7     10.0        7  
8      9.5        7  
9     10.5        5

&nbsp;



## Data Frames

### Learning about the data

We're going to continue to use the segment data for now. Don't forget to change this path. If the data is in the same folder as this workbook, you just need the filename.csv. 

In [39]:
import pandas as pd

path = "../data/segments.csv"
seg = pd.read_csv(path)

# .head() returns the first 5 rows of the dataframe
seg.head()

age   Income  Under18AtHome  HomeOwnership  subscribe   Segment
0  45.0  50033.0              4              0          0  Suburban
1  25.0  10835.0              3              0          0     Urban
2  46.0  63281.0              1              0          0  Suburban
3  40.0  46201.0              2              1          0  Suburban
4  41.0  49343.0              1              1          0  Suburban

Learning more about the data in the dataframe

* **.describe:** Useful to explore the whole dataframe (or at least the numeric columns).
* **.info:** Understand the data and data types. This is often where you can catch an early error.

In [40]:
seg.describe()

age         Income  Under18AtHome  HomeOwnership   subscribe
count  885.000000     853.000000    1000.000000    1000.000000  1000.00000
mean    37.875706   52772.724502       1.809000       0.405000     0.12200
std     17.743851   19114.767292       1.378557       0.491138     0.32745
min     19.000000    8653.000000       0.000000       0.000000     0.00000
25%     33.000000   42836.000000       1.000000       0.000000     0.00000
50%     38.000000   54570.000000       2.000000       0.000000     0.00000
75%     43.000000   65536.000000       3.000000       1.000000     0.00000
max    500.000000  129638.000000       9.000000       1.000000     1.00000

In [41]:
seg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   age            885 non-null    float64
 1   Income         853 non-null    float64
 2   Under18AtHome  1000 non-null   int64  
 3   HomeOwnership  1000 non-null   int64  
 4   subscribe      1000 non-null   int64  
 5   Segment        995 non-null    object 
dtypes: float64(2), int64(3), object(1)
memory usage: 47.0+ KB


In [42]:
seg.max(numeric_only=True)

age                 500.0
Income           129638.0
Under18AtHome         9.0
HomeOwnership         1.0
subscribe             1.0
dtype: float64

In [43]:
seg.mean(numeric_only=True)

age                 37.875706
Income           52772.724502
Under18AtHome        1.809000
HomeOwnership        0.405000
subscribe            0.122000
dtype: float64

In [44]:
seg.median(numeric_only=True)

age                 38.0
Income           54570.0
Under18AtHome        2.0
HomeOwnership        0.0
subscribe            0.0
dtype: float64

In [45]:
noNA = seg.dropna()
noNA.describe()

age         Income  Under18AtHome  HomeOwnership   subscribe
count  786.000000     786.000000     786.000000     786.000000  786.000000
mean    37.234097   51710.496183       1.805344       0.374046    0.122137
std     18.475424   18795.890690       1.352147       0.484184    0.327653
min     19.000000    8653.000000       0.000000       0.000000    0.000000
25%     32.000000   41935.750000       1.000000       0.000000    0.000000
50%     37.000000   53495.500000       2.000000       0.000000    0.000000
75%     42.000000   64631.000000       3.000000       1.000000    0.000000
max    500.000000  129638.000000       9.000000       1.000000    1.000000

&nbsp;


### Indexing and selecting data

There are 3 ways we are going to do this. Panda's has others, but we'll be good with 3.

* data [ ] : is an indexing operator. 
* data.loc[ ] : Looks for labels. Locates specific information.
* data.iloc[ ] : The "i" stands for integer bases, this looks for positions. 

#### [ ] as an indexing operator


Column access is fairly straightforward. First we look at the columns we have, and then we can subset some of them.

In [46]:
seg.columns

Index(['age', 'Income', 'Under18AtHome', 'HomeOwnership', 'subscribe',
       'Segment'],
      dtype='object')

In [47]:
seg['Segment']

0      Suburban
1         Urban
2      Suburban
3      Suburban
4      Suburban
         ...   
995    Suburban
996       Urban
997     ExUrban
998     ExUrban
999       Urban
Name: Segment, Length: 1000, dtype: object

In [48]:
#this also works
seg.Segment

0      Suburban
1         Urban
2      Suburban
3      Suburban
4      Suburban
         ...   
995    Suburban
996       Urban
997     ExUrban
998     ExUrban
999       Urban
Name: Segment, Length: 1000, dtype: object

We can pull out more than one at a time. Take note of the double '[[ ]]' brackets. The output from this is another data frame. 

In [49]:
a = seg[['Income', 'Segment']]
a

Income   Segment
0    50033.0  Suburban
1    10835.0     Urban
2    63281.0  Suburban
3    46201.0  Suburban
4    49343.0  Suburban
..       ...       ...
995  76813.0  Suburban
996  30868.0     Urban
997  57097.0   ExUrban
998  45875.0   ExUrban
999      NaN     Urban

[1000 rows x 2 columns]

We can use the index number for the row as well.

In [50]:
seg[51:56]

age   Income  Under18AtHome  HomeOwnership  subscribe   Segment
51  31.0  52516.0              2              0          0   ExUrban
52  42.0  61153.0              1              0          0  Suburban
53  21.0  29908.0              3              0          0     Urban
54  45.0  61353.0              1              0          0  Suburban
55  42.0      NaN              4              1          0  Suburban

#### loc & iloc

In Python's pandas library, loc and iloc are two methods used to access different parts of a DataFrame or Series. They are primarily used for indexing and selecting data. The key difference between them lies in how they handle indexing.

loc: label-based, which means that you have to specify the name of the rows and columns that you need to filter out. In other words, loc uses the labels of your data.

iloc: integer index-based. So here, you have to specify rows and columns by their integer index.


data[loc] can be much more powerful. 'loc' looks for labels within your data. The basic structure of .loc is this:

data.loc[row, column]

In [51]:
seg.loc[51:56, ['Income', 'Segment']]

Income     Segment
51  52516.0     ExUrban
52  61153.0    Suburban
53  29908.0       Urban
54  61353.0    Suburban
55      NaN    Suburban
56      NaN  ExSuburban

In [52]:
seg.loc[0:10]

age   Income  Under18AtHome  HomeOwnership  subscribe   Segment
0   45.0  50033.0              4              0          0  Suburban
1   25.0  10835.0              3              0          0     Urban
2   46.0  63281.0              1              0          0  Suburban
3   40.0  46201.0              2              1          0  Suburban
4   41.0  49343.0              1              1          0  Suburban
5   31.0  56718.0              1              0          0  Suburban
6   37.0  70625.0              4              1          1  Suburban
7   38.0  79416.0              2              1          1  Suburban
8   22.0  26357.0              2              0          0     Urban
9   40.0  72770.0              2              0          0  Suburban
10  39.0  56641.0              3              1          0  Suburban

In [53]:
seg.loc[seg.age > 35, ['Under18AtHome', 'Segment', 'age']]

Under18AtHome   Segment   age
0                4  Suburban  45.0
2                1  Suburban  46.0
3                2  Suburban  40.0
4                1  Suburban  41.0
6                4  Suburban  37.0
..             ...       ...   ...
992              1   ExUrban  36.0
993              2  Suburban  40.0
994              1  Suburban  51.0
995              3  Suburban  41.0
998              3   ExUrban  38.0

[552 rows x 3 columns]

Why does that work?

seg.age > 35 creates a boolean mask (True, False)

In [54]:
test = seg.age > 35
print(type(test))
test.head(10)

<class 'pandas.core.series.Series'>


0     True
1    False
2     True
3     True
4     True
5    False
6     True
7     True
8    False
9     True
Name: age, dtype: bool

In [55]:
seg.loc[(seg.age > 35) & (seg.Segment != 'Urban'), ['Under18AtHome', 'Segment', 'age']]

Under18AtHome   Segment   age
0                4  Suburban  45.0
2                1  Suburban  46.0
3                2  Suburban  40.0
4                1  Suburban  41.0
6                4  Suburban  37.0
..             ...       ...   ...
992              1   ExUrban  36.0
993              2  Suburban  40.0
994              1  Suburban  51.0
995              3  Suburban  41.0
998              3   ExUrban  38.0

[552 rows x 3 columns]

##### iloc

iloc looks for an index, and returns those values

The basic structure is the same as loc. The only difference is in how you identify the rows/columns.

data.iloc[row, column]

In [56]:
seg.iloc[0:10]

age   Income  Under18AtHome  HomeOwnership  subscribe   Segment
0  45.0  50033.0              4              0          0  Suburban
1  25.0  10835.0              3              0          0     Urban
2  46.0  63281.0              1              0          0  Suburban
3  40.0  46201.0              2              1          0  Suburban
4  41.0  49343.0              1              1          0  Suburban
5  31.0  56718.0              1              0          0  Suburban
6  37.0  70625.0              4              1          1  Suburban
7  38.0  79416.0              2              1          1  Suburban
8  22.0  26357.0              2              0          0     Urban
9  40.0  72770.0              2              0          0  Suburban


&nbsp;


### Aggregating and Grouping

In [57]:
import pandas as pd

path = "../data/segments.csv"
seg = pd.read_csv(path)
seg.head()

age   Income  Under18AtHome  HomeOwnership  subscribe   Segment
0  45.0  50033.0              4              0          0  Suburban
1  25.0  10835.0              3              0          0     Urban
2  46.0  63281.0              1              0          0  Suburban
3  40.0  46201.0              2              1          0  Suburban
4  41.0  49343.0              1              1          0  Suburban

In [58]:
seg.mean(numeric_only=True)

age                 37.875706
Income           52772.724502
Under18AtHome        1.809000
HomeOwnership        0.405000
subscribe            0.122000
dtype: float64

In [59]:
seg['age'].mean()
#I don't have to put "numeric only=True" here,
#because I am asking for a numeric column

37.87570621468927

In [60]:
seg['age'].median() 

38.0

#### GroupBy

Let's assume that we want to group the different groups in our "Segment" column, and return the means (average) for the columns with data. 

We start by creating a smaller data frame, to ensure the operation is clear, and then we will add in the rest. 

In [61]:
# make a smaller data set for now

df = seg.loc[0: , ['Segment', 'age']]
df.head()


Segment   age
0  Suburban  45.0
1     Urban  25.0
2  Suburban  46.0
3  Suburban  40.0
4  Suburban  41.0

In [62]:
df.groupby('Segment').mean()

age
Segment              
ExSuburban  59.785714
ExUrban     35.588957
Suburban    43.109974
Urban       23.911765

In [63]:
df.groupby('Segment').median()

age
Segment         
ExSuburban  59.0
ExUrban     36.0
Suburban    42.0
Urban       24.0

In [64]:
#let's go back to our larger dataset here
seg.groupby('Segment').mean()

age        Income  Under18AtHome  HomeOwnership  subscribe
Segment                                                                     
ExSuburban  59.785714  83329.136364       0.000000       0.653061   0.020408
ExUrban     35.588957  50707.901587       2.035294       0.332353   0.182353
Suburban    43.109974  64343.930667       2.044776       0.488273   0.095949
Urban       23.911765  20760.617647       1.116788       0.204380   0.094891

In [65]:
seg.groupby('Segment').median()

age   Income  Under18AtHome  HomeOwnership  subscribe
Segment                                                           
ExSuburban  59.0  84574.0            0.0            1.0        0.0
ExUrban     36.0  50580.0            2.0            0.0        0.0
Suburban    42.0  64149.0            2.0            0.0        0.0
Urban       24.0  20354.5            1.0            0.0        0.0

In [66]:
seg.groupby('Segment')[['HomeOwnership']].mean()

HomeOwnership
Segment                  
ExSuburban       0.653061
ExUrban          0.332353
Suburban         0.488273
Urban            0.204380

In [67]:
seg.set_index(['HomeOwnership'], append = True)


age   Income  Under18AtHome  subscribe   Segment
    HomeOwnership                                                   
0   0              45.0  50033.0              4          0  Suburban
1   0              25.0  10835.0              3          0     Urban
2   0              46.0  63281.0              1          0  Suburban
3   1              40.0  46201.0              2          0  Suburban
4   1              41.0  49343.0              1          0  Suburban
...                 ...      ...            ...        ...       ...
995 1              41.0  76813.0              3          0  Suburban
996 0              21.0  30868.0              1          0     Urban
997 1              35.0  57097.0              4          0   ExUrban
998 0              38.0  45875.0              3          0   ExUrban
999 1               NaN      NaN              0          0     Urban

[1000 rows x 5 columns]

#### .unstack

.unstack() is a method that can be used in combination with .groupby() to reshape the data in a DataFrame. When you perform a groupby operation, you often end up with a DataFrame or Series with a multi-level index (also known as a hierarchical index). The .unstack() method is used to pivot one of the levels of these multi-level indices, turning it into a column and reshaping the DataFrame.

In [68]:
seg.groupby(['Segment', 'HomeOwnership'])['age'].mean().fillna(0)

Segment     HomeOwnership
ExSuburban  0                58.181818
            1                60.823529
ExUrban     0                35.801843
            1                35.165138
Suburban    0                44.243781
            1                41.910526
Urban       0                23.990826
            1                23.592593
Name: age, dtype: float64

In [69]:
seg.groupby(['Segment', 'HomeOwnership'])['age'].mean().unstack().fillna(0)

HomeOwnership          0          1
Segment                            
ExSuburban     58.181818  60.823529
ExUrban        35.801843  35.165138
Suburban       44.243781  41.910526
Urban          23.990826  23.592593

#### Pivot tables



In [70]:
seg.pivot_table('age', index='Segment', columns='HomeOwnership', aggfunc='mean')

HomeOwnership          0          1
Segment                            
ExSuburban     58.181818  60.823529
ExUrban        35.801843  35.165138
Suburban       44.243781  41.910526
Urban          23.990826  23.592593

In [71]:
#we can have more than just one value (age)
#we do that by using an 'aggfunc' argument
seg.pivot_table(index='Segment', columns='HomeOwnership', aggfunc={'age':'mean', 'Income':'mean'})


Income                      age           
HomeOwnership             0             1          0          1
Segment                                                        
ExSuburban     80908.888889  85004.692308  58.181818  60.823529
ExUrban        51217.323944  49644.107843  35.801843  35.165138
Suburban       63450.168421  65261.848649  44.243781  41.910526
Urban          21200.045872  18986.629630  23.990826  23.592593

In [72]:
seg.pivot_table('age', index= 'Segment', columns='HomeOwnership', aggfunc='mean', margins = True)

HomeOwnership          0          1        All
Segment                                       
ExSuburban     58.181818  60.823529  59.785714
ExUrban        35.801843  35.165138  35.588957
Suburban       44.243781  41.910526  43.109974
Urban          23.990826  23.592593  23.911765
All            37.020446  39.262391  37.893303

## Joining Data

In [73]:
import pandas as pd



table1 = pd.DataFrame({'key': ['X4', 'X5', 'X6', 'X7', 'X8', 'X9'],
                   'A': ['Fact1', 'Fact2', 'Fact3', 'Fact4', 'Fact5', 'Fact6']})
table1

key      A
0  X4  Fact1
1  X5  Fact2
2  X6  Fact3
3  X7  Fact4
4  X8  Fact5
5  X9  Fact6

In [74]:
table2 = pd.DataFrame({'key': ['X1', 'X2', 'X3','X4', 'X5', 'X6'],
                      'B': ['one', 'two', 'three', 'four', 'five', 'six']})
table2

key      B
0  X1    one
1  X2    two
2  X3  three
3  X4   four
4  X5   five
5  X6    six

#### Merging dataframes

In Python, particularly when using the pandas library, you can perform database-style join operations, which are commonly used in SQL. Two of the most basic types of joins are the inner join and the outer join. These joins are used to combine data from two different tables (or DataFrames in pandas) based on a common key.

**Inner Join**
An inner join combines two DataFrames based on a common key and returns a new DataFrame that contains only the rows that have matching values in both of the original DataFrames. It's the most common type of join and is often used when you only want to keep rows that appear in both tables.



let's create an INNER JOIN using the merge function. This takes the two data frames, and returns the MATCHING rows (have the same 'key'.

In [75]:
table1.merge(table2, on='key')

key      A     B
0  X4  Fact1  four
1  X5  Fact2  five
2  X6  Fact3   six

An **outer join**, on the other hand, returns a DataFrame with all rows from both the original DataFrames, with matches from the other DataFrame where available and NaN elsewhere. This type of join is useful when you want to retain all information from both DataFrames, filling in gaps with NaN where necessary.Next a LEFT OUTER JOIN. This returns all the values on the left, and the matching values on the right.

In [76]:
table1.merge(table2, on='key', how='left')

key      A     B
0  X4  Fact1  four
1  X5  Fact2  five
2  X6  Fact3   six
3  X7  Fact4   NaN
4  X8  Fact5   NaN
5  X9  Fact6   NaN

Some less common joins...

Now a RIGHT OUTER JOIN. (All values from the table on the right, and only the matching keys from the table on the left)

In [77]:
table1.merge(table2, on='key', how='right')

key      A      B
0  X1    NaN    one
1  X2    NaN    two
2  X3    NaN  three
3  X4  Fact1   four
4  X5  Fact2   five
5  X6  Fact3    six

Almost there! Last a FULL OUTER JOIN

In [78]:
table1.merge(table2, on='key', how='outer')

key      A      B
0  X1    NaN    one
1  X2    NaN    two
2  X3    NaN  three
3  X4  Fact1   four
4  X5  Fact2   five
5  X6  Fact3    six
6  X7  Fact4    NaN
7  X8  Fact5    NaN
8  X9  Fact6    NaN

#### Dataframe.join

The DataFrame.join method defaults to join on the index with a left outer join. 

In [79]:
table1.set_index('key').join(table2.set_index('key'))

A     B
key             
X4   Fact1  four
X5   Fact2  five
X6   Fact3   six
X7   Fact4   NaN
X8   Fact5   NaN
X9   Fact6   NaN

In [80]:
table1.join(table2.set_index('key'), on='key')
  

key      A     B
0  X4  Fact1  four
1  X5  Fact2  five
2  X6  Fact3   six
3  X7  Fact4   NaN
4  X8  Fact5   NaN
5  X9  Fact6   NaN

#### Full example of joining two files

In [81]:
import pandas as pd

df_employees = pd.read_csv("../data/employees.csv")
df_projects = pd.read_csv("../data/projects.csv")

# Inner Join
inner_join_result = pd.merge(df_employees, df_projects, on='EmployeeID', how='inner')
inner_join_result.to_csv('inner_join_result.csv', index=False)

# Outer Join
outer_join_result = pd.merge(df_employees, df_projects, on='EmployeeID', how='outer')
outer_join_result.to_csv('outer_join_result.csv', index=False)


## Renaming Columns

In [82]:
mailer = {
    'Name' : ['Bobbie', 'Ayesha', 'Alanna', 'Miyah', 'Donnell', 'Dina'],
    'Last' : ['Huang', 'Melia', 'Thorp', 'Cope', 'Metcalfe', 'Smith'],
    'Current Address' :['912 Eastwood Dr', '118 Manchester Ave', '1724 Hulett Dr', 
                '851 Monterey Ct', '807 Greenbelt Cir','11013 Hannaway Dr'],
    'Last Active' :['1/9/2019', '1/10/2019', '2/28/2019', '3/22/2019', '4/16/2019', '6/3/2019'],
    'SALE': ['$100', '$164', '$32', '$46', '$550', '$149']

}

In [83]:
import pandas as pd
mailer = pd.DataFrame(mailer)
mailer


Name      Last     Current Address Last Active  SALE
0   Bobbie     Huang     912 Eastwood Dr    1/9/2019  $100
1   Ayesha     Melia  118 Manchester Ave   1/10/2019  $164
2   Alanna     Thorp      1724 Hulett Dr   2/28/2019   $32
3    Miyah      Cope     851 Monterey Ct   3/22/2019   $46
4  Donnell  Metcalfe   807 Greenbelt Cir   4/16/2019  $550
5     Dina     Smith   11013 Hannaway Dr    6/3/2019  $149

In [84]:
# change column names

mailer.columns

Index(['Name', 'Last', 'Current Address', 'Last Active', 'SALE'], dtype='object')

In [85]:
mailer.columns = ['first_name', 'last_name', 'current address', 'last active', 'sale']

In [86]:
mailer

first_name last_name     current address last active  sale
0     Bobbie     Huang     912 Eastwood Dr    1/9/2019  $100
1     Ayesha     Melia  118 Manchester Ave   1/10/2019  $164
2     Alanna     Thorp      1724 Hulett Dr   2/28/2019   $32
3      Miyah      Cope     851 Monterey Ct   3/22/2019   $46
4    Donnell  Metcalfe   807 Greenbelt Cir   4/16/2019  $550
5       Dina     Smith   11013 Hannaway Dr    6/3/2019  $149

In [87]:
mailer.columns = mailer.columns.str.replace(' ', '_')

In [88]:
mailer

first_name last_name     current_address last_active  sale
0     Bobbie     Huang     912 Eastwood Dr    1/9/2019  $100
1     Ayesha     Melia  118 Manchester Ave   1/10/2019  $164
2     Alanna     Thorp      1724 Hulett Dr   2/28/2019   $32
3      Miyah      Cope     851 Monterey Ct   3/22/2019   $46
4    Donnell  Metcalfe   807 Greenbelt Cir   4/16/2019  $550
5       Dina     Smith   11013 Hannaway Dr    6/3/2019  $149

In [89]:
# dictionary changes
mailer.rename(columns={
    'current_address' : 'address',
    'last_active': 'active'
}, inplace = True)

In [90]:
mailer


first_name last_name             address     active  sale
0     Bobbie     Huang     912 Eastwood Dr   1/9/2019  $100
1     Ayesha     Melia  118 Manchester Ave  1/10/2019  $164
2     Alanna     Thorp      1724 Hulett Dr  2/28/2019   $32
3      Miyah      Cope     851 Monterey Ct  3/22/2019   $46
4    Donnell  Metcalfe   807 Greenbelt Cir  4/16/2019  $550
5       Dina     Smith   11013 Hannaway Dr   6/3/2019  $149

### Changing rows

In [91]:
mailer.loc[0]

first_name             Bobbie
last_name               Huang
address       912 Eastwood Dr
active               1/9/2019
sale                     $100
Name: 0, dtype: object

In [92]:
mailer.loc[0, 'first_name'] = 'Bob' 
mailer

first_name last_name             address     active  sale
0        Bob     Huang     912 Eastwood Dr   1/9/2019  $100
1     Ayesha     Melia  118 Manchester Ave  1/10/2019  $164
2     Alanna     Thorp      1724 Hulett Dr  2/28/2019   $32
3      Miyah      Cope     851 Monterey Ct  3/22/2019   $46
4    Donnell  Metcalfe   807 Greenbelt Cir  4/16/2019  $550
5       Dina     Smith   11013 Hannaway Dr   6/3/2019  $149

In [93]:
mailer.loc[3, ['last_name', 'address']] = ['Cooper', '815 Monterey Ct'] 
mailer

first_name last_name             address     active  sale
0        Bob     Huang     912 Eastwood Dr   1/9/2019  $100
1     Ayesha     Melia  118 Manchester Ave  1/10/2019  $164
2     Alanna     Thorp      1724 Hulett Dr  2/28/2019   $32
3      Miyah    Cooper     815 Monterey Ct  3/22/2019   $46
4    Donnell  Metcalfe   807 Greenbelt Cir  4/16/2019  $550
5       Dina     Smith   11013 Hannaway Dr   6/3/2019  $149

In [94]:
mailer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   first_name  6 non-null      object
 1   last_name   6 non-null      object
 2   address     6 non-null      object
 3   active      6 non-null      object
 4   sale        6 non-null      object
dtypes: object(5)
memory usage: 372.0+ bytes


In [95]:
def convert_sign_remover(column_to_change):
    return float(column_to_change.replace("$","").replace(",",""))

mailer['sale'].apply(convert_sign_remover)

0    100.0
1    164.0
2     32.0
3     46.0
4    550.0
5    149.0
Name: sale, dtype: float64

In [96]:
mailer

first_name last_name             address     active  sale
0        Bob     Huang     912 Eastwood Dr   1/9/2019  $100
1     Ayesha     Melia  118 Manchester Ave  1/10/2019  $164
2     Alanna     Thorp      1724 Hulett Dr  2/28/2019   $32
3      Miyah    Cooper     815 Monterey Ct  3/22/2019   $46
4    Donnell  Metcalfe   807 Greenbelt Cir  4/16/2019  $550
5       Dina     Smith   11013 Hannaway Dr   6/3/2019  $149

In [97]:
mailer['spend'] = mailer['sale'].apply(convert_sign_remover)
mailer

first_name last_name             address     active  sale  spend
0        Bob     Huang     912 Eastwood Dr   1/9/2019  $100  100.0
1     Ayesha     Melia  118 Manchester Ave  1/10/2019  $164  164.0
2     Alanna     Thorp      1724 Hulett Dr  2/28/2019   $32   32.0
3      Miyah    Cooper     815 Monterey Ct  3/22/2019   $46   46.0
4    Donnell  Metcalfe   807 Greenbelt Cir  4/16/2019  $550  550.0
5       Dina     Smith   11013 Hannaway Dr   6/3/2019  $149  149.0